# Generated by Django 3.1.3 on 2021-05-04 08:39

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clusters_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionIn2D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='URL', max_length=30)),
                ('model', models.CharField(default='Modelname', max_length=30)),
                ('dimRed', models.CharField(default='LDA', max_length=30)),
                ('plot', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectionIn2D', to='clusters_app.basedata')),
            ],
        ),
    ]
