# Generated by Django 3.1.3 on 2021-05-04 13:01

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clusters_app', '0006_auto_20210504_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionin2d',
            name='kmeans',
            field=picklefield.fields.PickledObjectField(blank=True, default='SOME STRING', editable=False, null=True),
        ),
    ]
